channels:
  - defaults
  - conda-forge
  - bokeh
dependencies:
  - pandas
  - geojson
  - jupyter
  - panel
  - geoviews
  - iris
  - pyarrow
  - xlrd
  - pygal
  - cairosvg
  - hvplot
  - notebook
  - python
  - pip:
    - jupyter-server-proxy
